apiVersion: v2
name: paperless-ngx
description: "A community-supported supercharged version of paperless: scan, index and archive all your physical documents"
type: application
version: 0.26.0
# renovate datasource=docker depName=ghcr.io/paperless-ngx/paperless-ngx
appVersion: 2.17.1
kubeVersion: ">=1.22.0-0"
keywords:
  - documents
  - ocr
  - paper
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.0.1
  - name: postgresql
    version: 16.7.17
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 21.0.2
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 21.2.10
    condition: redis.enabled
sources:
  - https://github.com/paperless-ngx/paperless-ngx
