apiVersion: v1
entries:
  hoarder:
  - apiVersion: v2
    appVersion: 0.21.0
    created: "2025-01-20T16:41:48.69827+01:00"
    dependencies:
    - name: common
      repository: https://bjw-s.github.io/helm-charts
      version: 3.6.1
    description: A Helm chart for https://github.com/hoarder-app/hoarder
    digest: 537f7ba2b0a0c324685a80aef93c8284a27e42574817dd887207167bfd9234cc
    name: hoarder
    type: application
    urls:
    - hoarder-0.0.1.tgz
    version: 0.0.1
generated: "2025-01-20T16:41:48.695664+01:00"
