---
controllers:
  # Configure the main controller
  main:
    containers:
      # Configure the main application container
      main:
        image:
          # -- image repository
          repository: ghcr.io/hoarder-app/hoarder
          # -- image tag
          tag: 3.6.1
        # -- environment variables
        env:
          # - name: OPENAI_API_KEY:
          #   value: ...
          - name: MEILI_ADDR
            value: http://meilisearch:7700
          - name: BROWSER_WEB_URL
            value: http://chrome:9222
          - name: DATA_DIR
            value: &data_dir "/data"
          - name: MEILI_MASTER_KEY
            value: &meili_master_key "master_key"
          - name: NEXTAUTH_URL
            value: &nextauth_url http://localhost:3000
          - name: NEXTAUTH_SECRET
            value: &nextauth_secret "nextauthSecret"

      # Configure the chrome sidecar
      chrome:
        # dependsOn: main
        image:
          # -- image repository
          repository:  gcr.io/zenika-hub/alpine-chrome
          # -- image tag
          tag: 123
        # -- command
        command:
          - --no-sandbox
          - --disable-gpu
          - --disable-dev-shm-usage
          - --remote-debugging-address=0.0.0.0
          - --remote-debugging-port=9222
          - --hide-scrollbars

      meilisearch:
        # dependsOn: main
        image:
          repository: getmeili/meilisearch
          tag: v1.11.1
        # -- environment variables
        env:
          - name: MEILI_NO_ANALYTICS
            value: true
          - name: DATA_DIR
            value: *data_dir
          - name: MEILI_ADDR
            value: "http://127.0.0.1:7700"
          - name: MEILI_MASTER_KEY
            value: *meili_master_key
          - name: NEXTAUTH_URL
            value: *nextauth_url
          - name: NEXTAUTH_SECRET
            value: *nextauth_secret

service:
  # Configure a service for the main application
  main:
    controller: main
    type: ClusterIP
    ports:
      http:
        port: 3000
  chrome:
    controller: chrome
    type: ClusterIP
    ports:
      http:
        port: 9222
  meilisearch:
    controller: meilisearch
    type: ClusterIP
    ports:
      http:
        port: 7700

ingress:
  # Configure an Ingress for the main application
  main:
    className: ""
    hosts:
      - host: &host "example.local"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - *host

# -- Configure persistence settings for the chart under this key.
persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    # storageClass: ""
    accessMode: ReadWriteOnce
    size: 10Gi
    advancedMounts:
      main:
        main:
          - path: /data