---
apiVersion: v2
name: checkmk
description: checkmk
type: application
version: 0.1.12
appVersion: 2.3.0
sources:
  - https://docs.checkmk.com/latest/en/introduction_docker.html
maintainers:
  - name: bym0
    email: timo@bergen.digital
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.0.1
