---
common:
  defaultPodOptions:
    securityContext:
      fsGroup: 1000

  controllers:
    # Configure the main controller
    main:
      enabled: true

      initContainers:
        init-config:
          image:
            repository: checkmk/check-mk-raw
            tag: 2.3.0-latest
          command:
            - sh
            - -c
            - |
              # Create necessary directories
              mkdir -p /omd/sites
              mkdir -p /omd/sites/cmk/tmp
              
              # Create site user if it doesn't exist
              if ! id -u cmk > /dev/null 2>&1; then
                useradd -u 1000 -g 1000 -d /omd/sites/cmk cmk
              fi
              
              # Initialize the Checkmk site if it doesn't exist
              if [ ! -f /omd/sites/cmk/etc/omd/site.conf ]; then
                omd create cmk
                omd start cmk
              fi
              
              # Set proper permissions
              chown -R 1000:1000 /omd/sites
              chown -R 1000:1000 /omd/sites/cmk/tmp

      containers:
        # Configure the main application container
        main:
          image:
            # -- image repository
            repository: checkmk/check-mk-raw
            # -- image tag
            tag: 2.3.0-latest
          # -- environment variables
          env:
            - name: TZ
              value: Europe/Berlin

  # -- Configure persistence settings for the chart under this key.
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      storageClass: "" # set storageClass
      accessMode: ReadWriteOnce
      size: 50Gi
      advancedMounts:
        main:
          main:
            - path: /omd/sites
          init-config:
            - path: /omd/sites

    tmpfs:
      enabled: true
      type: emptyDir
      medium: Memory
      advancedMounts:
        main:
          main:
            - path: /opt/omd/sites/cmk/tmp
          init-config:
            - path: /opt/omd/sites/cmk/tmp

  service:
    # Configure a service for the main application
    main:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 5000
        httpother:
          port: 8000

  ingress:
    # Configure an Ingress for the main application
    main:
      enabled: true
      className: "" # set class
      annotations: {}
      hosts:
        - host: "" # set domain
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: checkmk-tls
          hosts:
            - "" # set domain